CreateUserRequest=CreateUserResponse:username=username, role=role
DepositRequest=TransactionResponse:id=relatedAccountId,balance=amount
TransferRequest=TransferResponse:senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,amount=amount
UpdateProfileRequest=CustomerResponse:name=name