name: Build and Publish Tests Image on Source Changes

# триггер
on:
  push:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs: # аналог этапов
  run-tests:
    name: Build, Test and Publish
    runs-on: ubuntu-latest
    steps: # шаги конкретной job
      - name: Checkout repository # копируем файлы репозитория внутрь CI агента
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          # ubuntu-maven-123
          restore-keys: | 
            ${{ runner.os }}-maven-

      - name: Check code style
        run: ./mvnw checkstyle:check

      - name: Set up services
        working-directory: infra/docker_compose
        run: bash restart_docker.sh

      - name: Run tests
        run: ./mvnw clean test -q -Pall
        env:
          APIBASEURL: http://localhost:4111
          UIBASEURL: http://nginx:80

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nbank-tests:${{ github.sha }}
